[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["ALL", "ANN"]
extend-select = ["ANN204", "ANN205"]

# Resolve common pydocstyle conflicts and allow prints
ignore = ["D203", "D212", "T201"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["stangastaden-parking-finder"]
combine-as-imports = true
force-sort-within-sections = true
